version: '3.8'
services:
  todolist-db:
    image: 'postgres:15'
    container_name: todolist-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres